name: Build and push

on:
  workflow_dispatch:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: Actions
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: galang8664
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: orkunergun/docker:ubuntu

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
